[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crafting = "FHqRv6fKfxXiXLe1xWeTxwwK7nEEoCBjR54shEvsQptC"
item_nft = "E3f7Fab3eH6J6DMcyd4yoXhtrmFCMJhu21zZKfjK33ha"
magic_token = "Gy652wSGwe1tiAhAMNb4xcVsEcVVJD1qvVDeLdDDKPCf"
marketplace = "H9qAUvfX5qCncku494UC1t2Yg6SXmEsinNuPdcmWWQLU"
resource_manager = "691PdUpsPbrTAWHkiBNXHjk49FMWoBrTRUsmsyNT7Tjm"
search = "8hbndEaekE2x7qKYBdWhVqqm5sHbnpZZ7pJkgdZ3xrhg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
